theme: jekyll-theme-minimal
title: works
description: Website project I created or involved. Most sites are just made for fun with hard-liver.
navigation:
  - title: blog
    url: https://zenkarsha.github.io/blog/
  - title: twitter
    url: https://twitter.com/zenkarsha/
