theme: jekyll-theme-minimal
title: works
description: Website project I created or involved. Most sites are just made for fun with hard-liver.
navigation:
  - title: biography
    url: https://zenkarsha.github.io/biography/
  - title: poetry
    url: https://zenkarsha.github.io/poetry/
  - title: muse
    url: https://zenkarsha.github.io/muse/
  - title: whisper
    url: https://zenkarsha.github.io/whisper/
  - title: twitter
    url: https://twitter.com/zenkarsha/
